In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
from sklearn.datasets import load_iris
iris=load_iris()

In [3]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [4]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [5]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [6]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
df=pd.DataFrame(iris.data)
df

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [9]:
df['Flower']=pd.DataFrame(iris.target)
df.head()

0    1    2    3  Flower
0  5.1  3.5  1.4  0.2       0
1  4.9  3.0  1.4  0.2       0
2  4.7  3.2  1.3  0.2       0
3  4.6  3.1  1.5  0.2       0
4  5.0  3.6  1.4  0.2       0

**Train and test split**

In [10]:
X=df.iloc[:,:-1]
X.shape

(150, 4)

In [11]:
y=df.iloc[:,-1]
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Flower, Length: 150, dtype: int64

In [12]:
X.shape,y.shape

((150, 4), (150,))

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=45)
X_train.shape,X_test.shape

((105, 4), (45, 4))

**Feature engineering and Cross Validation**

In [14]:
from sklearn.model_selection import StratifiedKFold
cv=StratifiedKFold(shuffle=True,random_state=45)

**Model development**

In [15]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(multi_class='ovr')
lr

LogisticRegression(multi_class='ovr')

In [16]:
lr.fit(X_train,y_train)

LogisticRegression(multi_class='ovr')

In [17]:
y_pred=lr.predict(X_test)
y_pred

array([0, 0, 2, 0, 0, 0, 0, 2, 2, 2, 0, 2, 2, 2, 1, 0, 2, 2, 0, 1, 1, 2,
       2, 1, 0, 2, 1, 1, 0, 1, 1, 1, 1, 2, 0, 2, 0, 0, 1, 0, 0, 1, 0, 2,
       1])

In [18]:
lr.predict_proba(X_test)

array([[8.85969814e-01, 1.14021575e-01, 8.61054375e-06],
       [9.09418466e-01, 9.05453870e-02, 3.61467725e-05],
       [2.11672333e-04, 3.55422647e-01, 6.44365681e-01],
       [7.65038538e-01, 2.34950352e-01, 1.11097031e-05],
       [7.74900863e-01, 2.25088660e-01, 1.04763903e-05],
       [9.24918255e-01, 7.50339188e-02, 4.78257286e-05],
       [7.49580929e-01, 2.50412065e-01, 7.00576004e-06],
       [1.91954298e-05, 2.99097720e-01, 7.00883085e-01],
       [1.73733857e-03, 4.68017109e-01, 5.30245552e-01],
       [2.36879246e-04, 1.81503871e-01, 8.18259249e-01],
       [8.68004748e-01, 1.31986953e-01, 8.29888353e-06],
       [1.40812583e-04, 2.65288644e-01, 7.34570543e-01],
       [9.78187993e-04, 4.43593150e-01, 5.55428662e-01],
       [3.46527167e-04, 3.60637107e-01, 6.39016366e-01],
       [1.56973560e-03, 5.22583426e-01, 4.75846838e-01],
       [8.31479235e-01, 1.68515600e-01, 5.16522535e-06],
       [6.00777375e-04, 2.04729835e-01, 7.94669388e-01],
       [1.03593111e-03, 4.14101

In [19]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score
cm=confusion_matrix(y_test,y_pred)
print('confusion matrix \n', cm)
ass=accuracy_score(y_test,y_pred)
print('accuracy' , ass)
ps=precision_score(y_test,y_pred,average='macro')
print('precission',ps)
rec=recall_score(y_test,y_pred,average='macro')
print('recall',rec)
f1=f1_score(y_test,y_pred,average='micro')
print('f1 score',f1)

confusion matrix 
 [[17  0  0]
 [ 0 11  2]
 [ 0  2 13]]
accuracy 0.9111111111111111
precission 0.9042735042735043
recall 0.9042735042735043
f1 score 0.9111111111111111


# **Grid Search CV**

Hyper parameter tuning

In [20]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(multi_class='ovr')


In [21]:
Solver=['lbfgs', 'newton-cholesky', 'newton-cg', 'sag', 'saga', 'liblinear']
Penalty=['l1', 'l2','elasticnet']
c=[0.001,0.01,0.005,0.05,1,10,100]
max_iter= [100, 200, 300]
params=dict(solver=Solver,penalty=Penalty,C=c)
params

{'solver': ['lbfgs',
  'newton-cholesky',
  'newton-cg',
  'sag',
  'saga',
  'liblinear'],
 'penalty': ['l1', 'l2', 'elasticnet'],
 'C': [0.001, 0.01, 0.005, 0.05, 1, 10, 100]}

In [22]:
grid=GridSearchCV(estimator=lr,param_grid=params,scoring='accuracy',cv=cv)
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=45, shuffle=True),
             estimator=LogisticRegression(multi_class='ovr'),
             param_grid={'C': [0.001, 0.01, 0.005, 0.05, 1, 10, 100],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'newton-cholesky', 'newton-cg',
                                    'sag', 'saga', 'liblinear']},
             scoring='accuracy')

In [23]:
grid.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which 

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=45, shuffle=True),
             estimator=LogisticRegression(multi_class='ovr'),
             param_grid={'C': [0.001, 0.01, 0.005, 0.05, 1, 10, 100],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'newton-cholesky', 'newton-cg',
                                    'sag', 'saga', 'liblinear']},
             scoring='accuracy')

In [24]:
y_pred=grid.predict(X_test)
y_pred

array([0, 0, 1, 0, 0, 0, 0, 2, 2, 2, 0, 2, 2, 2, 1, 0, 2, 2, 0, 1, 2, 1,
       2, 1, 0, 2, 1, 1, 0, 1, 1, 1, 1, 2, 0, 2, 0, 0, 1, 0, 0, 1, 0, 1,
       1])

In [25]:
grid.best_estimator_

LogisticRegression(C=10, multi_class='ovr', solver='sag')

In [26]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score
cm=confusion_matrix(y_test,y_pred)
print('confusion matrix \n', cm)
ass=accuracy_score(y_test,y_pred)
print('accuracy' , ass)
ps=precision_score(y_test,y_pred,average='macro')
print('precission',ps)
rec=recall_score(y_test,y_pred,average='macro')
print('recall',rec)
f1=f1_score(y_test,y_pred,average='macro')
print('f1 score',f1)

confusion matrix 
 [[17  0  0]
 [ 0 12  1]
 [ 0  3 12]]
accuracy 0.9111111111111111
precission 0.9076923076923077
recall 0.9076923076923077
f1 score 0.9047619047619048


# **RandomSearchCV**

In [27]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(multi_class='ovr')


In [28]:
Solver=['lbfgs', 'newton-cholesky', 'newton-cg', 'sag', 'saga', 'liblinear']
Penalty=['l1', 'l2','elasticnet']
c=[0.001,0.01,0.005,0.05,1,10,100]
max_iter= [100, 200, 300]
params=dict(solver=Solver,penalty=Penalty,C=c,max_iter=max_iter)
params

{'solver': ['lbfgs',
  'newton-cholesky',
  'newton-cg',
  'sag',
  'saga',
  'liblinear'],
 'penalty': ['l1', 'l2', 'elasticnet'],
 'C': [0.001, 0.01, 0.005, 0.05, 1, 10, 100],
 'max_iter': [100, 200, 300]}

In [29]:
rand=RandomizedSearchCV(estimator=lr,param_distributions=params,scoring='accuracy',cv=cv,random_state=45,n_jobs=-1)
rand

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=45, shuffle=True),
                   estimator=LogisticRegression(multi_class='ovr'), n_jobs=-1,
                   param_distributions={'C': [0.001, 0.01, 0.005, 0.05, 1, 10,
                                              100],
                                        'max_iter': [100, 200, 300],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['lbfgs', 'newton-cholesky',
                                                   'newton-cg', 'sag', 'saga',
                                                   'liblinear']},
                   random_state=45, scoring='accuracy')

In [32]:
rand.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:425: FitFailedWarning: 
20 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 729, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 1152, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py", line 1169, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "/usr

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=45, shuffle=True),
                   estimator=LogisticRegression(multi_class='ovr'), n_jobs=-1,
                   param_distributions={'C': [0.001, 0.01, 0.005, 0.05, 1, 10,
                                              100],
                                        'max_iter': [100, 200, 300],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['lbfgs', 'newton-cholesky',
                                                   'newton-cg', 'sag', 'saga',
                                                   'liblinear']},
                   random_state=45, scoring='accuracy')

In [34]:
y_pred=rand.predict(X_test)
y_pred

array([0, 0, 1, 0, 0, 0, 0, 2, 2, 2, 0, 2, 2, 2, 1, 0, 2, 2, 0, 1, 1, 1,
       2, 1, 0, 2, 1, 1, 0, 1, 1, 1, 1, 2, 0, 2, 0, 0, 1, 0, 0, 1, 0, 1,
       1])

In [35]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score
cm=confusion_matrix(y_test,y_pred)
print('confusion matrix \n', cm)
ass=accuracy_score(y_test,y_pred)
print('accuracy' , ass)
ps=precision_score(y_test,y_pred,average='macro')
print('precission',ps)
rec=recall_score(y_test,y_pred,average='macro')
print('recall',rec)
f1=f1_score(y_test,y_pred,average='macro')
print('f1 score',f1)

confusion matrix 
 [[17  0  0]
 [ 0 13  0]
 [ 0  3 12]]
accuracy 0.9333333333333333
precission 0.9375
recall 0.9333333333333332
f1 score 0.9284802043422733
