# **#   K nearest Neighbour Classifier**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
from sklearn.datasets import make_classification
X,y=make_classification(n_samples=1000,n_features=9,n_clusters_per_class=1,n_classes=4,shuffle=True,random_state=18)
X.shape,y.shape

((1000, 9), (1000,))

In [ ]:
X

array([[-2.12445174,  3.45684651, -0.61257842, ..., -0.90119516,
         1.47270092,  1.96704426],
       [-0.3408915 ,  2.39909437,  1.91496284, ..., -0.40842375,
         1.52532508,  0.4033813 ],
       [ 0.10344515,  1.1398442 , -0.61091699, ...,  0.73538688,
         0.41752224, -0.89463637],
       ...,
       [ 1.89629444, -0.86776394,  0.64531   , ..., -1.03259641,
        -0.49802359, -0.90676141],
       [ 0.80231089, -0.07360826,  0.77562161, ...,  0.85320037,
        -0.03762683,  1.29338812],
       [ 0.29755481,  1.92576213,  0.72459311, ..., -1.49116984,
        -0.82282647,  0.91052663]])

In [ ]:
df=pd.DataFrame(X)
df.head()

0         1         2         3         4         5         6  \
0 -2.124452  3.456847 -0.612578  0.274257 -0.409280  0.592490 -0.901195   
1 -0.340891  2.399094  1.914963 -0.031204 -0.748271  0.302072 -0.408424   
2  0.103445  1.139844 -0.610917  0.183787 -1.020323 -0.571431  0.735387   
3 -1.577797 -0.922889 -0.137094  0.990908  2.193088 -1.726596  2.092009   
4 -1.152436 -0.523482  0.075648 -0.125753 -1.327092  1.076970 -1.451814   

          7         8  
0  1.472701  1.967044  
1  1.525325  0.403381  
2  0.417522 -0.894636  
3 -0.389772 -0.882008  
4  0.029433 -0.949928

In [ ]:
y

array([0, 0, 3, 1, 0, 0, 1, 1, 2, 0, 1, 3, 1, 1, 1, 1, 2, 2, 1, 0, 0, 2,
       0, 3, 0, 2, 2, 1, 0, 3, 3, 0, 1, 2, 2, 0, 1, 1, 0, 2, 2, 1, 0, 2,
       1, 2, 0, 2, 2, 0, 3, 3, 1, 2, 3, 2, 2, 3, 1, 2, 2, 1, 0, 0, 0, 2,
       3, 2, 3, 1, 3, 0, 3, 3, 1, 1, 3, 3, 3, 1, 3, 2, 1, 3, 0, 3, 2, 0,
       3, 1, 2, 0, 2, 0, 1, 1, 0, 2, 2, 2, 0, 2, 1, 1, 0, 3, 3, 3, 2, 1,
       3, 1, 3, 3, 0, 1, 1, 3, 1, 1, 3, 3, 1, 0, 3, 3, 1, 3, 1, 3, 1, 0,
       2, 2, 2, 1, 3, 2, 0, 3, 3, 3, 3, 1, 1, 3, 0, 3, 0, 0, 2, 0, 2, 1,
       3, 2, 0, 3, 1, 2, 3, 0, 1, 0, 0, 0, 3, 1, 3, 0, 1, 0, 0, 0, 0, 2,
       2, 2, 3, 0, 2, 1, 1, 1, 1, 3, 1, 0, 1, 1, 3, 1, 1, 0, 3, 0, 3, 1,
       2, 0, 2, 0, 3, 0, 2, 1, 3, 3, 2, 0, 2, 2, 3, 1, 2, 1, 3, 1, 1, 1,
       2, 2, 0, 1, 3, 2, 3, 1, 3, 0, 3, 3, 0, 3, 0, 3, 1, 0, 0, 0, 0, 3,
       2, 0, 2, 1, 0, 0, 3, 2, 1, 2, 2, 2, 0, 0, 1, 0, 3, 1, 2, 3, 2, 0,
       3, 3, 3, 3, 0, 2, 0, 2, 1, 2, 0, 1, 1, 0, 3, 3, 2, 3, 1, 3, 0, 3,
       0, 1, 2, 1, 3, 0, 1, 0, 1, 3, 2, 1, 1, 0, 1,

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y)
X_train.shape,y_train.shape

((750, 9), (750,))

**K-nearest neighbour classifier**

algorithm, metric are dfault

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knnc=KNeighborsClassifier(n_neighbors=5)
knnc.fit(X_train,y_train)
y_pred=knnc.predict(X_test)
y_pred

array([1, 2, 1, 3, 3, 2, 1, 2, 1, 2, 3, 0, 3, 2, 0, 0, 3, 2, 3, 2, 2, 2,
       0, 0, 2, 0, 2, 0, 3, 0, 0, 0, 1, 3, 1, 1, 1, 1, 0, 0, 3, 3, 3, 2,
       2, 3, 3, 2, 2, 1, 1, 0, 3, 0, 2, 0, 1, 0, 3, 3, 1, 2, 3, 2, 0, 3,
       0, 2, 2, 1, 1, 1, 3, 1, 2, 1, 1, 0, 2, 2, 2, 0, 2, 1, 0, 2, 3, 1,
       2, 1, 1, 2, 3, 2, 2, 1, 1, 3, 1, 2, 0, 1, 1, 3, 2, 0, 2, 1, 2, 3,
       2, 1, 3, 3, 3, 2, 0, 3, 1, 1, 1, 3, 2, 3, 1, 2, 2, 1, 0, 1, 2, 0,
       0, 1, 3, 1, 3, 1, 2, 2, 1, 1, 3, 1, 0, 3, 1, 1, 3, 0, 1, 3, 0, 0,
       2, 2, 0, 0, 1, 1, 0, 3, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 3, 0, 3, 1,
       0, 0, 1, 0, 1, 2, 1, 3, 0, 3, 2, 1, 1, 0, 0, 1, 2, 1, 0, 2, 0, 3,
       0, 0, 3, 3, 2, 3, 2, 2, 2, 0, 1, 3, 0, 1, 3, 1, 3, 3, 0, 0, 1, 3,
       0, 1, 3, 2, 0, 2, 1, 2, 2, 1, 2, 3, 0, 2, 0, 2, 0, 2, 1, 3, 1, 2,
       3, 3, 0, 1, 3, 3, 3, 1])

In [ ]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[41  7  8  0]
 [11 53  1  1]
 [ 9  7 51  1]
 [ 0  3  1 56]]
0.804
              precision    recall  f1-score   support

           0       0.67      0.73      0.70        56
           1       0.76      0.80      0.78        66
           2       0.84      0.75      0.79        68
           3       0.97      0.93      0.95        60

    accuracy                           0.80       250
   macro avg       0.81      0.80      0.81       250
weighted avg       0.81      0.80      0.81       250



**Hyper Parameter Tuning**

using gridsearch and Randomized search cv

weights: str = "uniform", algorithm: str = "auto", leaf_size: int = 30, p: int = 2, metric: str = "minkowski", metric_params: Any | None = None, n_jobs: Any | None = None) -> None

In [ ]:

weights=['uniform', 'distance']
n_neighbors=[4,5,6,7]
algorithm=['ball_tree', 'kd_tree', 'brute']
p=[1,2]
params=dict(
    weights=weights,
    n_neighbors=n_neighbors,
    algorithm=algorithm,
    p=p
)
params

{'weights': ['uniform', 'distance'],
 'n_neighbors': [4, 5, 6, 7],
 'algorithm': ['ball_tree', 'kd_tree', 'brute'],
 'p': [1, 2]}

In [ ]:
knnc=KNeighborsClassifier()
knnc

KNeighborsClassifier()

In [ ]:
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV
#gridsearchcv
grid=GridSearchCV(estimator=knnc,param_grid=params,scoring='accuracy', n_jobs=-1)
grid

GridSearchCV(estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'algorithm': ['ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [4, 5, 6, 7], 'p': [1, 2],
                         'weights': ['uniform', 'distance']},
             scoring='accuracy')

In [ ]:
grid.fit(X_train,y_train)

GridSearchCV(estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'algorithm': ['ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [4, 5, 6, 7], 'p': [1, 2],
                         'weights': ['uniform', 'distance']},
             scoring='accuracy')

In [ ]:
y_pred=grid.predict(X_test)
y_pred

array([1, 2, 1, 3, 3, 2, 1, 2, 1, 2, 3, 0, 3, 2, 2, 0, 3, 2, 3, 2, 2, 2,
       0, 0, 2, 2, 2, 1, 3, 0, 0, 0, 1, 3, 1, 1, 1, 0, 0, 0, 3, 3, 3, 2,
       2, 3, 3, 2, 2, 1, 1, 0, 3, 0, 2, 0, 1, 0, 3, 3, 1, 2, 3, 2, 0, 3,
       0, 0, 2, 1, 1, 1, 3, 1, 2, 1, 1, 2, 2, 2, 2, 0, 2, 1, 0, 2, 3, 1,
       2, 1, 1, 2, 3, 2, 2, 1, 1, 3, 1, 2, 0, 1, 1, 3, 2, 0, 2, 0, 2, 3,
       2, 1, 3, 3, 3, 2, 0, 3, 1, 1, 1, 3, 2, 3, 1, 2, 2, 1, 0, 1, 2, 0,
       2, 1, 3, 0, 3, 1, 2, 2, 1, 1, 1, 1, 0, 3, 3, 1, 3, 0, 1, 3, 0, 0,
       2, 2, 0, 0, 1, 1, 0, 3, 0, 0, 1, 0, 1, 2, 0, 0, 0, 1, 3, 0, 3, 1,
       2, 0, 2, 0, 1, 2, 1, 3, 0, 3, 2, 1, 1, 1, 0, 1, 2, 1, 0, 2, 1, 3,
       0, 0, 3, 3, 2, 3, 2, 2, 2, 0, 2, 3, 0, 1, 3, 1, 3, 3, 0, 1, 1, 3,
       2, 0, 3, 2, 1, 0, 1, 2, 2, 1, 2, 2, 0, 2, 0, 2, 0, 2, 1, 3, 1, 2,
       3, 3, 1, 0, 3, 3, 3, 1])

In [ ]:
rand.best_params_

{'weights': 'distance', 'p': 1, 'n_neighbors': 5, 'algorithm': 'brute'}

In [ ]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[41  7  8  0]
 [ 9 56  1  0]
 [ 6  3 59  0]
 [ 0  2  1 57]]
0.852
              precision    recall  f1-score   support

           0       0.73      0.73      0.73        56
           1       0.82      0.85      0.84        66
           2       0.86      0.87      0.86        68
           3       1.00      0.95      0.97        60

    accuracy                           0.85       250
   macro avg       0.85      0.85      0.85       250
weighted avg       0.85      0.85      0.85       250



**Randomized Searched CV**

In [ ]:
rand=RandomizedSearchCV(estimator=knnc,param_distributions=params,scoring='accuracy', n_jobs=-1,)
rand.fit(X_train,y_train)
y_pred=rand.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[41  7  8  0]
 [ 9 56  1  0]
 [ 6  3 59  0]
 [ 0  2  1 57]]
0.852
              precision    recall  f1-score   support

           0       0.73      0.73      0.73        56
           1       0.82      0.85      0.84        66
           2       0.86      0.87      0.86        68
           3       1.00      0.95      0.97        60

    accuracy                           0.85       250
   macro avg       0.85      0.85      0.85       250
weighted avg       0.85      0.85      0.85       250



# **K Nearest Neighbour Regression**

In [ ]:
from sklearn.neighbors import KNeighborsRegressor
knnr=KNeighborsRegressor(n_neighbors=5)
knnr.fit(X_train,y_train)
y_pred=knnr.predict(X_test)
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = mean_squared_error(y_test, y_pred, squared=False)
r2 = r2_score(y_test, y_pred)
print(f"Mean Absolute Error (MAE): {mae}")
print(f"Mean Squared Error (MSE): {mse}")
print(f"Root Mean Squared Error (RMSE): {rmse}")
print(f"R-squared (R²): {r2}")

Mean Absolute Error (MAE): 0.35919999999999996
Mean Squared Error (MSE): 0.31664000000000003
Root Mean Squared Error (RMSE): 0.5627077394171863
R-squared (R²): 0.7310264216592366


**Hyper parametertuning**

In [ ]:
knnr=KNeighborsRegressor()
grid=GridSearchCV(estimator=knnr,param_grid=params,scoring='accuracy', n_jobs=-1)
grid.fit(X_train,y_train)
y_pred=grid.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = mean_squared_error(y_test, y_pred, squared=False)
r2 = r2_score(y_test, y_pred)
print(f"Mean Absolute Error (MAE): {mae}")
print(f"Mean Squared Error (MSE): {mse}")
print(f"Root Mean Squared Error (RMSE): {rmse}")
print(f"R-squared (R²): {r2}")

Mean Absolute Error (MAE): 0.323
Mean Squared Error (MSE): 0.30375
Root Mean Squared Error (RMSE): 0.5511351921262151
R-squared (R²): 0.7419759840165271


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_search.py:979: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan]
  warnings.warn(


In [ ]:
rand.best_params_

{'weights': 'distance', 'p': 1, 'n_neighbors': 5, 'algorithm': 'brute'}

In [ ]:
rand=RandomizedSearchCV(estimator=knnr,param_distributions=params,scoring='accuracy', n_jobs=-1,)
rand.fit(X_train,y_train)
y_pred=rand.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = mean_squared_error(y_test, y_pred, squared=False)
r2 = r2_score(y_test, y_pred)
print(f"Mean Absolute Error (MAE): {mae}")
print(f"Mean Squared Error (MSE): {mse}")
print(f"Root Mean Squared Error (RMSE): {rmse}")
print(f"R-squared (R²): {r2}")

Mean Absolute Error (MAE): 0.36856454050655324
Mean Squared Error (MSE): 0.2979767022102017
Root Mean Squared Error (RMSE): 0.5458724230167721
R-squared (R²): 0.7468801798393823


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_search.py:979: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan nan nan nan nan nan]
  warnings.warn(
